### ISSUE TITLE
BetterTwitter bug

### ISSUE THREAD

**Issue by SpikeTheGuy** [sapondanaisriwan/BetterTwitter#1]
Hello, my name is SpikeTheGuy. I use your stylus install 'BetterTwitter' for my account. Currently, there seems to be a bug that is causing the icons for likes, retweets etc between comments to be squashed together, which at the time of typing this wasn't an issue until half an hour or so back (images provided below)
![BetterTwitterBugExample](https://github.com/sapondanaisriwan/BetterTwitter/assets/146134359/6a68f25a-055c-4eb9-bd1c-2bfd968b910a)
![BetterTwitterBugCode](https://github.com/sapondanaisriwan/BetterTwitter/assets/146134359/7b4bc8d1-ef26-4bca-8a9e-76dc1d698f95)
If you could look into this and see what the issue is, I'd be grateful. Thank you for extension and for your time reading.

**Comment by sapondanaisriwan** [comment]
I just release v1.0.6, please let me know it works for you or not.

**Comment by SpikeTheGuy** [comment]
Hey there. Sorry for the late response, but I checked it out and the update works. The bug's no longer present. Thank you : )
